/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAlertasRouteImport } from './routes/_authenticated/alertas'
import { Route as AuthenticatedCuentaRouteImport } from './routes/_authenticated/cuenta'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEscanearRouteImport } from './routes/_authenticated/escanear'
import { Route as AuthenticatedIngenierosRouteImport } from './routes/_authenticated/ingenieros'
import { Route as AuthenticatedInicioRouteImport } from './routes/_authenticated/inicio'
import { Route as AuthenticatedMovimientosRouteImport } from './routes/_authenticated/movimientos'
import { Route as AuthenticatedReportesRouteImport } from './routes/_authenticated/reportes'
import { Route as AuthenticatedSitiosRouteImport } from './routes/_authenticated/sitios'
import { Route as AuthenticatedActivosIndexRouteImport } from './routes/_authenticated/activos/index'
import { Route as AuthenticatedActivosAssetIdRouteImport } from './routes/_authenticated/activos/$assetId'
import { Route as AuthenticatedAdminAlertasRouteImport } from './routes/_authenticated/admin/alertas'
import { Route as AuthenticatedAdminReportesRouteImport } from './routes/_authenticated/admin/reportes'
import { Route as ApiPublicPasswordResetRouteImport } from './routes/api/public/password-reset'
import { Route as ApiPublicPasswordUpdateRouteImport } from './routes/api/public/password-update'
import { Route as ApiReportsInventoryRouteImport } from './routes/api/reports/inventory'
import { Route as ApiReportsMovementsRouteImport } from './routes/api/reports/movements'
import { Route as ApiPublicAuthSplatRouteImport } from './routes/api/public/auth/$'
import { Route as ApiPublicRestSplatRouteImport } from './routes/api/public/rest/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAlertasRoute = AuthenticatedAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCuentaRoute = AuthenticatedCuentaRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEscanearRoute = AuthenticatedEscanearRouteImport.update({
  id: '/escanear',
  path: '/escanear',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIngenierosRoute = AuthenticatedIngenierosRouteImport.update({
  id: '/ingenieros',
  path: '/ingenieros',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInicioRoute = AuthenticatedInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMovimientosRoute =
  AuthenticatedMovimientosRouteImport.update({
    id: '/movimientos',
    path: '/movimientos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportesRoute = AuthenticatedReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSitiosRoute = AuthenticatedSitiosRouteImport.update({
  id: '/sitios',
  path: '/sitios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActivosIndexRoute =
  AuthenticatedActivosIndexRouteImport.update({
    id: '/activos/',
    path: '/activos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedActivosAssetIdRoute =
  AuthenticatedActivosAssetIdRouteImport.update({
    id: '/activos/$assetId',
    path: '/activos/$assetId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAlertasRoute =
  AuthenticatedAdminAlertasRouteImport.update({
    id: '/admin/alertas',
    path: '/admin/alertas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminReportesRoute =
  AuthenticatedAdminReportesRouteImport.update({
    id: '/admin/reportes',
    path: '/admin/reportes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicPasswordResetRoute = ApiPublicPasswordResetRouteImport.update({
  id: '/api/public/password-reset',
  path: '/api/public/password-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPasswordUpdateRoute = ApiPublicPasswordUpdateRouteImport.update({
  id: '/api/public/password-update',
  path: '/api/public/password-update',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportsInventoryRoute = ApiReportsInventoryRouteImport.update({
  id: '/api/reports/inventory',
  path: '/api/reports/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportsMovementsRoute = ApiReportsMovementsRouteImport.update({
  id: '/api/reports/movements',
  path: '/api/reports/movements',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthSplatRoute = ApiPublicAuthSplatRouteImport.update({
  id: '/api/public/auth/$',
  path: '/api/public/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRestSplatRoute = ApiPublicRestSplatRouteImport.update({
  id: '/api/public/rest/$',
  path: '/api/public/rest/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/alertas': typeof AuthenticatedAlertasRoute
  '/cuenta': typeof AuthenticatedCuentaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/escanear': typeof AuthenticatedEscanearRoute
  '/ingenieros': typeof AuthenticatedIngenierosRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/movimientos': typeof AuthenticatedMovimientosRoute
  '/reportes': typeof AuthenticatedReportesRoute
  '/sitios': typeof AuthenticatedSitiosRoute
  '/activos/$assetId': typeof AuthenticatedActivosAssetIdRoute
  '/admin/alertas': typeof AuthenticatedAdminAlertasRoute
  '/admin/reportes': typeof AuthenticatedAdminReportesRoute
  '/api/public/password-reset': typeof ApiPublicPasswordResetRoute
  '/api/public/password-update': typeof ApiPublicPasswordUpdateRoute
  '/api/reports/inventory': typeof ApiReportsInventoryRoute
  '/api/reports/movements': typeof ApiReportsMovementsRoute
  '/activos/': typeof AuthenticatedActivosIndexRoute
  '/api/public/auth/$': typeof ApiPublicAuthSplatRoute
  '/api/public/rest/$': typeof ApiPublicRestSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/alertas': typeof AuthenticatedAlertasRoute
  '/cuenta': typeof AuthenticatedCuentaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/escanear': typeof AuthenticatedEscanearRoute
  '/ingenieros': typeof AuthenticatedIngenierosRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/movimientos': typeof AuthenticatedMovimientosRoute
  '/reportes': typeof AuthenticatedReportesRoute
  '/sitios': typeof AuthenticatedSitiosRoute
  '/activos/$assetId': typeof AuthenticatedActivosAssetIdRoute
  '/admin/alertas': typeof AuthenticatedAdminAlertasRoute
  '/admin/reportes': typeof AuthenticatedAdminReportesRoute
  '/api/public/password-reset': typeof ApiPublicPasswordResetRoute
  '/api/public/password-update': typeof ApiPublicPasswordUpdateRoute
  '/api/reports/inventory': typeof ApiReportsInventoryRoute
  '/api/reports/movements': typeof ApiReportsMovementsRoute
  '/activos': typeof AuthenticatedActivosIndexRoute
  '/api/public/auth/$': typeof ApiPublicAuthSplatRoute
  '/api/public/rest/$': typeof ApiPublicRestSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/alertas': typeof AuthenticatedAlertasRoute
  '/_authenticated/cuenta': typeof AuthenticatedCuentaRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/escanear': typeof AuthenticatedEscanearRoute
  '/_authenticated/ingenieros': typeof AuthenticatedIngenierosRoute
  '/_authenticated/inicio': typeof AuthenticatedInicioRoute
  '/_authenticated/movimientos': typeof AuthenticatedMovimientosRoute
  '/_authenticated/reportes': typeof AuthenticatedReportesRoute
  '/_authenticated/sitios': typeof AuthenticatedSitiosRoute
  '/_authenticated/activos/$assetId': typeof AuthenticatedActivosAssetIdRoute
  '/_authenticated/admin/alertas': typeof AuthenticatedAdminAlertasRoute
  '/_authenticated/admin/reportes': typeof AuthenticatedAdminReportesRoute
  '/api/public/password-reset': typeof ApiPublicPasswordResetRoute
  '/api/public/password-update': typeof ApiPublicPasswordUpdateRoute
  '/api/reports/inventory': typeof ApiReportsInventoryRoute
  '/api/reports/movements': typeof ApiReportsMovementsRoute
  '/_authenticated/activos/': typeof AuthenticatedActivosIndexRoute
  '/api/public/auth/$': typeof ApiPublicAuthSplatRoute
  '/api/public/rest/$': typeof ApiPublicRestSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/alertas'
    | '/cuenta'
    | '/dashboard'
    | '/escanear'
    | '/ingenieros'
    | '/inicio'
    | '/movimientos'
    | '/reportes'
    | '/sitios'
    | '/activos/$assetId'
    | '/admin/alertas'
    | '/admin/reportes'
    | '/api/public/password-reset'
    | '/api/public/password-update'
    | '/api/reports/inventory'
    | '/api/reports/movements'
    | '/activos/'
    | '/api/public/auth/$'
    | '/api/public/rest/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/alertas'
    | '/cuenta'
    | '/dashboard'
    | '/escanear'
    | '/ingenieros'
    | '/inicio'
    | '/movimientos'
    | '/reportes'
    | '/sitios'
    | '/activos/$assetId'
    | '/admin/alertas'
    | '/admin/reportes'
    | '/api/public/password-reset'
    | '/api/public/password-update'
    | '/api/reports/inventory'
    | '/api/reports/movements'
    | '/activos'
    | '/api/public/auth/$'
    | '/api/public/rest/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/alertas'
    | '/_authenticated/cuenta'
    | '/_authenticated/dashboard'
    | '/_authenticated/escanear'
    | '/_authenticated/ingenieros'
    | '/_authenticated/inicio'
    | '/_authenticated/movimientos'
    | '/_authenticated/reportes'
    | '/_authenticated/sitios'
    | '/_authenticated/activos/$assetId'
    | '/_authenticated/admin/alertas'
    | '/_authenticated/admin/reportes'
    | '/api/public/password-reset'
    | '/api/public/password-update'
    | '/api/reports/inventory'
    | '/api/reports/movements'
    | '/_authenticated/activos/'
    | '/api/public/auth/$'
    | '/api/public/rest/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicPasswordResetRoute: typeof ApiPublicPasswordResetRoute
  ApiPublicPasswordUpdateRoute: typeof ApiPublicPasswordUpdateRoute
  ApiReportsInventoryRoute: typeof ApiReportsInventoryRoute
  ApiReportsMovementsRoute: typeof ApiReportsMovementsRoute
  ApiPublicAuthSplatRoute: typeof ApiPublicAuthSplatRoute
  ApiPublicRestSplatRoute: typeof ApiPublicRestSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/alertas': {
      id: '/_authenticated/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AuthenticatedAlertasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cuenta': {
      id: '/_authenticated/cuenta'
      path: '/cuenta'
      fullPath: '/cuenta'
      preLoaderRoute: typeof AuthenticatedCuentaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/escanear': {
      id: '/_authenticated/escanear'
      path: '/escanear'
      fullPath: '/escanear'
      preLoaderRoute: typeof AuthenticatedEscanearRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ingenieros': {
      id: '/_authenticated/ingenieros'
      path: '/ingenieros'
      fullPath: '/ingenieros'
      preLoaderRoute: typeof AuthenticatedIngenierosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inicio': {
      id: '/_authenticated/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedInicioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/movimientos': {
      id: '/_authenticated/movimientos'
      path: '/movimientos'
      fullPath: '/movimientos'
      preLoaderRoute: typeof AuthenticatedMovimientosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reportes': {
      id: '/_authenticated/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof AuthenticatedReportesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sitios': {
      id: '/_authenticated/sitios'
      path: '/sitios'
      fullPath: '/sitios'
      preLoaderRoute: typeof AuthenticatedSitiosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activos/': {
      id: '/_authenticated/activos/'
      path: '/activos'
      fullPath: '/activos/'
      preLoaderRoute: typeof AuthenticatedActivosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activos/$assetId': {
      id: '/_authenticated/activos/$assetId'
      path: '/activos/$assetId'
      fullPath: '/activos/$assetId'
      preLoaderRoute: typeof AuthenticatedActivosAssetIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/alertas': {
      id: '/_authenticated/admin/alertas'
      path: '/admin/alertas'
      fullPath: '/admin/alertas'
      preLoaderRoute: typeof AuthenticatedAdminAlertasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/reportes': {
      id: '/_authenticated/admin/reportes'
      path: '/admin/reportes'
      fullPath: '/admin/reportes'
      preLoaderRoute: typeof AuthenticatedAdminReportesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/password-reset': {
      id: '/api/public/password-reset'
      path: '/api/public/password-reset'
      fullPath: '/api/public/password-reset'
      preLoaderRoute: typeof ApiPublicPasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/password-update': {
      id: '/api/public/password-update'
      path: '/api/public/password-update'
      fullPath: '/api/public/password-update'
      preLoaderRoute: typeof ApiPublicPasswordUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reports/inventory': {
      id: '/api/reports/inventory'
      path: '/api/reports/inventory'
      fullPath: '/api/reports/inventory'
      preLoaderRoute: typeof ApiReportsInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reports/movements': {
      id: '/api/reports/movements'
      path: '/api/reports/movements'
      fullPath: '/api/reports/movements'
      preLoaderRoute: typeof ApiReportsMovementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/$': {
      id: '/api/public/auth/$'
      path: '/api/public/auth/$'
      fullPath: '/api/public/auth/$'
      preLoaderRoute: typeof ApiPublicAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/rest/$': {
      id: '/api/public/rest/$'
      path: '/api/public/rest/$'
      fullPath: '/api/public/rest/$'
      preLoaderRoute: typeof ApiPublicRestSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAlertasRoute: typeof AuthenticatedAlertasRoute
  AuthenticatedCuentaRoute: typeof AuthenticatedCuentaRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEscanearRoute: typeof AuthenticatedEscanearRoute
  AuthenticatedIngenierosRoute: typeof AuthenticatedIngenierosRoute
  AuthenticatedInicioRoute: typeof AuthenticatedInicioRoute
  AuthenticatedMovimientosRoute: typeof AuthenticatedMovimientosRoute
  AuthenticatedReportesRoute: typeof AuthenticatedReportesRoute
  AuthenticatedSitiosRoute: typeof AuthenticatedSitiosRoute
  AuthenticatedActivosAssetIdRoute: typeof AuthenticatedActivosAssetIdRoute
  AuthenticatedAdminAlertasRoute: typeof AuthenticatedAdminAlertasRoute
  AuthenticatedAdminReportesRoute: typeof AuthenticatedAdminReportesRoute
  AuthenticatedActivosIndexRoute: typeof AuthenticatedActivosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAlertasRoute: AuthenticatedAlertasRoute,
  AuthenticatedCuentaRoute: AuthenticatedCuentaRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEscanearRoute: AuthenticatedEscanearRoute,
  AuthenticatedIngenierosRoute: AuthenticatedIngenierosRoute,
  AuthenticatedInicioRoute: AuthenticatedInicioRoute,
  AuthenticatedMovimientosRoute: AuthenticatedMovimientosRoute,
  AuthenticatedReportesRoute: AuthenticatedReportesRoute,
  AuthenticatedSitiosRoute: AuthenticatedSitiosRoute,
  AuthenticatedActivosAssetIdRoute: AuthenticatedActivosAssetIdRoute,
  AuthenticatedAdminAlertasRoute: AuthenticatedAdminAlertasRoute,
  AuthenticatedAdminReportesRoute: AuthenticatedAdminReportesRoute,
  AuthenticatedActivosIndexRoute: AuthenticatedActivosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicPasswordResetRoute: ApiPublicPasswordResetRoute,
  ApiPublicPasswordUpdateRoute: ApiPublicPasswordUpdateRoute,
  ApiReportsInventoryRoute: ApiReportsInventoryRoute,
  ApiReportsMovementsRoute: ApiReportsMovementsRoute,
  ApiPublicAuthSplatRoute: ApiPublicAuthSplatRoute,
  ApiPublicRestSplatRoute: ApiPublicRestSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
